# Generated by Django 3.1.5 on 2021-02-02 05:52

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# noinspection PyPep8,PyPep8,PyPep8
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BLI', 'Bali'), ('MDA', 'Madeira'), ('PST', 'Paris trip'), ('FOS', 'F1 stage'), ('HAB', 'Hot air balloon'), ('RSS', 'Route 66'), ('MIL', 'Milano'), ('ITL', 'Italy'), ('FRC', 'France'), ('RME', 'Rome'), ('VER', 'Versailles'), ('LDA', 'London'), ('LDB', 'London'), ('HLX', 'Halifax'), ('ENG', 'England'), ('NAN', 'NONE')], default='NAN', max_length=3)),
                ('remaining_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='NAN')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=225)),
                ('surname', models.CharField(default='', editable=False, max_length=225)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 2, 2, 7, 52, 27, 174789))),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
